### ISSUE TITLE
local demo docker is cannot detect GPU

### ISSUE THREAD

**Issue by heyufan1995** [facebookresearch/sam2#354]
Hi:
The local demo with the docker cannot detect GPUs in currenct `docker-compose.yaml`. 
I need to modify the yaml file to utilize GPU by 
adding a `deploy` to the end of `docker-compose.yaml`
```
    environment:
      - SERVER_ENVIRONMENT=DEV
      - GUNICORN_WORKERS=1
      # Inference API needs to have at least 2 threads to handle an incoming
      # parallel cancel propagation request
      - GUNICORN_THREADS=2
      - GUNICORN_PORT=5000
      - API_URL=http://localhost:7263
      - DEFAULT_VIDEO_PATH=gallery/05_default_juggle.mp4
      # # ffmpeg/video encode settings
      - FFMPEG_NUM_THREADS=1
      - VIDEO_ENCODE_CODEC=libx264
      - VIDEO_ENCODE_CRF=23
      - VIDEO_ENCODE_FPS=24
      - VIDEO_ENCODE_MAX_WIDTH=1280
      - VIDEO_ENCODE_MAX_HEIGHT=720
      - VIDEO_ENCODE_VERBOSE=False
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```
