### ISSUE TITLE
Train sam2 on SA-1B

### ISSUE THREAD

**Issue by xings19** [facebookresearch/sam2#432]
Hi @hpichlerbio, thanks for your interest. One way to finetune on your custom **image** only dataset is to follow the last [section](https://github.com/facebookresearch/sam2/tree/main/training#training-on-images-and-videos) in the training README but remove the video dataset from the mix. The config would look something like this (removing the video dataset from the mix):

```yaml
data:
  train:
    _target_: training.dataset.sam2_datasets.TorchTrainMixedDataset 
    phases_per_epoch: ${phases_per_epoch} # Chunks a single epoch into smaller phases
    batch_sizes: # List of batch sizes corresponding to each dataset
    - ${bs1} # Batch size of dataset 1
    datasets:
    # Custom Image dataset
    - _target_: training.dataset.vos_dataset.VOSDataset
      training: true
      video_dataset:
        _target_: training.dataset.vos_raw_dataset.CustomImageDataset # Your custom Dataset class
        img_folder: ${path_to_img_folder}
        gt_folder: ${path_to_gt_folder}
        file_list_txt: ${path_to_train_filelist} # Optional
      sampler:
        _target_: training.dataset.vos_sampler.RandomUniformSampler
        num_frames: 1
        max_num_objects: ${max_num_objects_per_image}
      transforms: ${image_transforms}
    shuffle: True
    num_workers: ${num_train_workers}
    pin_memory: True
    drop_last: True
    collate_fn:
    _target_: training.utils.data_utils.collate_fn
    _partial_: true
    dict_key: all
```

Note that if you'd like to use your custom dataset, you should implement your own dataset class (similar to [`SA1BRawDataset`](https://github.com/facebookresearch/sam2/blob/52198ead0eb13ae8270bea6ca768ef175f5bf167/training/dataset/vos_raw_dataset.py#L148)). If your dataset is in SA1B format, you can directly use `SA1BRawDataset`. Please let me know if you have further questions

_Originally posted by @haithamkhedr in https://github.com/facebookresearch/sam2/issues/347#issuecomment-2389785209_
