### ISSUE TITLE
How to fix the image encoder when finetuning SAM2

### ISSUE THREAD

**Issue by WangKan0128** [facebookresearch/sam2#667]
Hello, thank you for your contribution. I followed your training code and fine-tuned it on MOSE.  I am wandering how to fix the image encoder, and others mdule, e.g., memory encoder,  when performing the finetuning.

Thanks

**Comment by chanjunha0** [comment]
In `sam2/configs/sam2.1_training/sam2.1_hiera_b+_MOSE_finetune.yaml`

Set `layer_decay_value` to 0 to freeze the image encoder.

```
param_group_modifiers:
      - _target_: training.optimizer.layer_decay_param_modifier
        _partial_: True
        layer_decay_value: 0.9 #Set this to 0
        apply_to: 'image_encoder.trunk'
        overrides:
          - pattern: '*pos_embed*'
            value: 1.0
```
